### ISSUE TITLE
Invalid Token 

### ISSUE THREAD

**Issue by antoine-gagne** [openmhealth/omh-dsu-ri#6]
Hi,
I saw the ticket created by Arutchelvi90 and it helped me get over the same problem. Looking back to see where it comes from, it seems like the [example code provided](https://github.com/openmhealth/omh-dsu-ri/blob/master/resources/rdbms/common/oauth2-sample-data.sql) instructs to insert a row with dataPoints as a value for resource_ids.
Since everywhere else it seems like dataPoint (without s) is used, I am guessing that the example insert contains a typo?

**Comment by emersonf** [comment]
Thanks for reporting @antoine-gagne. I'll reconcile the API RAML, the examples, and the code and post an update later this week.

**Comment by emersonf** [comment]
So that bug was fixed last May, but we never cut a release. Most of the attention was being put on other projects, and we've only recently given this storage endpoint some attention.

The correct resource ID is `dataPoints` (plural), the typo is in `OAuth2Properties.java`. The next release, due tomorrow, will fix this.

**Comment by emersonf** [comment]
This is fixed in release [0.1.0](https://github.com/openmhealth/omh-dsu-ri/releases/tag/v0.1.0). Thanks for reporting!
